python updated to 3.11 fixed issues #30 and #26
 TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.

 thanks to https://github.com/Zulko/moviepy/issues/2025#issuecomment-1767953504